rails/projects/gatecart/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # devise_for :admins, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  

  root "homepage#index"

  get "homepage/index"

  get 'register', to: 'users#register'
#  post 'register', to: 'users#create'


  get 'log_in', to: 'sessions#log_in'
  post 'log_in', to: 'sessions#create'

  delete 'log_out', to: 'sessions#destroy'

  resources :users
  
  resources :products
  
  post 'search', to: 'products#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  #custom help route
  get "help", to: "help#help_page"
end

rails/projects/gatecart/app/models/product.rb
class Product < ApplicationRecord
    belongs_to :admin
    
    paginates_per 3

    enum :category, [:Electronics, :Cloths, :Toys, :Furniture, :"Smart Phones", :Cosmetics, :Kitchen, :Appliance]

    validates :name, presence: true, length: {minimum: 3, maximum: 50}
    validates :category, presence: true#, inclusion: { in: %w(electronics, cloths, toys, furniture, smart_phones)
    validates :price, presence: true
    
    # mount_uploader :image, ImageUploader #also you need to add column :image (sring) to products 

    has_one_attached :image #, dependent: :destroy
    has_rich_text :description
    # after_destroy :delete_images

    private

        # def delete_images
        #     FileUtils.remove_dir("public/uploads/product/image/#{self.id}") if File.directory?("public/uploads/product/image/#{self.id}")
        # end
end

rails/projects/gatecart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!, only: %i[ new create edit update destroy]
    before_action :set_admin, only: %i[ index show new create edit update destroy]
    before_action :convert_category_to_integer
    # PRODUCT_PER_PAGE = 3

    
    def index

        if admin_signed_in?
            if params[:search]
                @products = @admin.products.where("name LIKE ?", Product.sanitize_sql_like(params[:search])+"%")
                @products = @products.page(params[:page])
            else
                @products = @admin.products.page(params[:page])
            end
        else
            if params[:search]
                @products = Product.where("name LIKE ?", Product.sanitize_sql_like(params[:search])+"%")
                @products = @products.page(params[:page])
            else
                @products = Product.all.page(params[:page])
            end
        end        
    end


    def show
        @product = Product.find_by(id: params[:id])
    end


    def new
        @product = @admin.products.new

    end


    def create
        @product = @admin.products.new(product_params)

        #respond_to do |format|
            if @product.save

                redirect_to product_path(@product.id), notice: "Product Added."
                # format.html { redirect_to demo_url(@demo), notice: "Demo was successfully created." }
                # format.json { render :show, status: :created, location: @demo }
            else
                render :new, status: :unprocessable_entity
                # format.html { render :new, status: :unprocessable_entity }
                # format.json { render json: @demo.errors, status: :unprocessable_entity }
            end
        #end

    end

    def edit
        @product = @admin.products.find_by(id: params[:id])

    end

    def update
        @product = @admin.products.find_by(id: params[:id])

        if @product.update(product_params)
            redirect_to product_path(@product), notice: "Product Updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @product = Product.find_by(id: params[:id])

        @product.destroy
        
        redirect_to products_path, status: :see_other #303
    end

    private
        # def check_session
        #     if session[:user_id]
        #         return true
        #     else
        #         redirect_to log_in_path, alert: "Please Login"
        #     end
        # end

        def set_admin
            @admin = current_admin
        end

        # def total_pages(product_count)
        #     if( (product_count % PRODUCT_PER_PAGE) == 0)
        #         return (product_count / PRODUCT_PER_PAGE)
        #     else
        #         return (product_count / PRODUCT_PER_PAGE) + 1
        #     end
        # end

        def convert_category_to_integer
            params[:category] = params[:category].to_i
        end

        def product_params
            params.require(:product).permit(:name, :category, :price, :description, :image, :search)#, :page_number)
        end
end

rails/projects/gatecart/app/views/products/_form.html.erb
<div class="form-outer-div">
<%= form_with model: @product, local: true, class: "add-product-form-class" do |form| %>

        <%= form.label :name %> <br>
        <%= form.text_field :name %> <br>
        <p class="errors"> <%= @product.errors.full_messages_for(:name).first %> </p>

        <%= form.label :category %> <br>
        <%= form.select :category, options_for_select(Product.categories.map {|key, value| [key.titleize, Product.categories.key(value)]}, @product.category) %>
        <p class="errors"> <%= @product.errors.full_messages_for(:category).first%> </p> 
    
    
        <%= form.label :price %> <br>
        <%= form.number_field :price %>
        <p class="errors"> <%= @product.errors.full_messages_for(:price).first%> </p>
    
        <%= form.label :description %> <br>
        <%= form.rich_text_area :description %>

        <%= form.label :image %> <br>
        <%= form.file_field :image, onchange: "loadImage(event);"%>    
        <%= image_tag "", id: "preview"%>
    
        <%= form.submit "Save Product" %>
<% end %>


<script>
    var loadImage = function(event){
        var preview = document.getElementById("preview");
        preview.src = URL.createObjectURL(event.target.files[0]);

        preview.onload = function(){
            URL.revokeObjectURL(preview.src) // free memory
        }
    };
</script>

<div>

rails/projects/gatecart/app/views/products/edit.html.erb
<%= render "form", product: @product%>

rails/projects/gatecart/app/views/products/index.html.erb
<%# @name="products & Vlogs" %>
<div class="search-div">
<%= form_with url: products_path,  method: :get, local: false, class: "search-form" do |form| %>
<%# form_with url: products_path,  method: :post, remote: true, class: "search-form" do |form| %>
    <%= form.text_field :search, placeholder: "Search...", class: "search-bar" %>
    <%= form.submit "Search", class: "search-button"%>
<% end %>
</div> <br>

<div class="grid-container-product">
    
    <% @products.each do |product| %>
        <div class="grid-item-product">
            
            <%= image_tag product.image, class: "index-product-image-class" if product.image.attached?%> <br> 
            <%# image_tag product.image.url, class: "index-product-image-class" if product.image?%>
            
            <%= product.name  %> <br>
            Price: <%= product.price %> <br><br>
            <%= link_to("Show", product) %>

            <% if admin_signed_in? %>
                <%= link_to("Edit", edit_product_path(product)) %>
                <%= link_to "Delete", product_path(product), data: {
                                                                    turbo_method: :delete,
                                                                    turbo_confirm: "Are You Sure?\nYou want to delete '#{product.name}'" } %>
            <% end %>

        </div>
    <% end %>
</div>

<%= paginate @products %>

rails/projects/gatecart/app/views/products/new.html.erb
<% product= @product %>
<%= render partial: "form"%>

rails/projects/gatecart/app/views/products/show.html.erb
<div class="grid-container">

    <div class="grid-item-product-image"> 
        <%= image_tag @product.image if @product.image.attached?%> <br>
    </div>

    <div class="grid-item-product-text">
        <div class= "product-name"> <%= @product.name%> </div>
        <div class= "product-price"><b>Price: </b> <%= @product.price%> </div>
        <div class= "product-category"><b>Category: </b><%= @product.category%></div>

        <div class="trix-content"> <%= @product.description %> </div>
    </div>

</div>



<% if admin_signed_in? %>
<div class= "grid-item-product-buttons">
    <div class="product-button-bottom"> <%= link_to("Edit This Product", edit_product_path(@product)) %> </div>
    <div class= "product-button-bottom"> <%= link_to "Delete This Product", product_path(@product), data: 
                                                                            {turbo_method: :delete,
                                                                            turbo_confirm: "Are You Sure?\nYou want to delete '#{@product.name}' "}  %> </div>
<div>
<% end %>