rails/projects/gatecart/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # devise_for :admins, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  

  root "homepage#index"

  get "homepage/index"

  get 'register', to: 'users#register'
#  post 'register', to: 'users#create'


  get 'log_in', to: 'sessions#log_in'
  post 'log_in', to: 'sessions#create'

  delete 'log_out', to: 'sessions#destroy'

  resources :users
  
  resources :products
  
  post 'search', to: 'products#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  #custom help route
  get "help", to: "help#help_page"
end

rails/projects/gatecart/app/views/shared/_footer.html.erb
<!-- Footer content -->

<footer >
  <div class="footer-content">
    
    <h3>GateCart.com</h3>
    
    <!-- 
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, ducimus amet! Ipsum sint, nobis tempore error expedita molestias, magnam blanditiis illum incidunt at dolorum molestiae, ipsa reiciendis cumque quod harum.
    </p> 
    -->

  </div>
</footer>
  

rails/projects/gatecart/app/views/shared/_header.html.erb
<!-- Header Content -->
<nav class="header-class">

	<div class="logo">
		<p>GateCart</p>
	</div>

	<ul>
			<li> <%= link_to "Home", products_path %> </li>
			<li> <%= link_to "Products", products_path %> </li>

		<% if admin_signed_in? %>
        	<li> <%= link_to "Add Product", new_product_path %> </li>  
        	<li> <%= button_to "Log Out", destroy_admin_session_path, method: :delete %> </li>
    	
		<% elsif session[:user_id] %>
        	<li> <%= button_to "Log Out", log_out_path, method: :delete %> </li>
    	
		<% else %>
        	<li> <%= link_to "Register", root_path %> </li>
        	<li> <%= link_to "Log In", root_path	 %> </li>
    	
		<% end %>

	</ul>

</nav>

rails/projects/gatecart/app/views/shared/_navbar.html.erb
  <!-- Navbar content -->

<div class="nav_class">
  <ul>
      <li> <%= link_to "Home", products_path %> </li>
      <li> <%= link_to "Products", products_path %> </li>

    <% if admin_signed_in? %>
        <li> <%= link_to "Add Product", new_product_path %> </li>  

        <li class= "header_right_buttons"> <%= link_to "Log Out", destroy_admin_session_path, data: {turbo_method: :delete}%> </li>
    <% elsif session[:user_id] %>
        <li class= "header_right_buttons"> <%= link_to "Log Out", log_out_path, data: {turbo_method: :delete}%> </li>
    <% else %>
        <li class= "header_right_buttons"> <%= link_to "Register", root_path %> </li>
        <li class= "header_right_buttons"> <%= link_to "Log In", root_path	 %> </li>
    <% end %>
    
  </ul>
</div>